os: linux
language: node_js
node_js: 10
jobs:
  include:
    - name: "build"
      script:
        - CI=false npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: build
        on:
          branch: master
